version: '3.8'

services:
  spiderfootsy:
    build:
      context: ./
      dockerfile: ./Dockerfile.full
    volumes:
      - ../spiderfoot-data:/var/lib/spiderfoot
      - ../spiderfoot-web-data:/home/spiderfoot/spiderfoot/static
      - ../spiderfoot-web-data-templates:/home/spiderfoot/spiderfoot/templates
    container_name: spidertown
    ports:
      - "5001:5001"
    restart: no
    image: spiderfoot
  
volumes:
  spiderfoot-data:
  spiderfoot-web-data:
  spiderfoot-web-data-templates:
