services:
  spiderfootsy:
    build:
      context: ./
      dockerfile: ./Dockerfile.mine
    volumes:
      - ../spiderfoot-data:/var/lib/spiderfoot
      - ../spiderfoot-logs:/var/lib/spiderfoot/log
    container_name: spidertown
    ports:
      - "5001:5001"
    restart: no
    image: spiderfoot
  
volumes:
  spiderfoot-data:
  spiderfoot-logs:
