services:
  spiderfoot:
    image: ghcr.io/elliotberry/spiderfoot:latest
    pull_policy: always
    ports:
      - "5001:5001"
    volumes:
      - spiderfoot-data:/var/lib/spiderfoot
    restart: unless-stopped

volumes:
  spiderfoot-data:
