services:
  spiderfoot:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ../spiderfoot-data:/var/lib/spiderfoot
    ports:
      - "5001:5001"
      - "9051:9051"
    restart: no
  
volumes:
  spiderfoot-data:
