version: "3"

services:
  spiderfoot:
    build:
      context: ./
    volumes:
      - ../spiderfoot-data:/var/lib/spiderfoot
      - ../spiderfoot-web-data:/home/spiderfoot/spiderfoot/static
      - ../spiderfoot-web-data-templates:/home/spiderfoot/spiderfoot/templates
    container_name: spider-city
    ports:
      - "5001:5001"
    restart: unless-stopped
    image: spiderfoot
  
volumes:
  spiderfoot-data:
  spiderfoot-web-data:
  spiderfoot-web-data-templates:
